CREATE TABLE songs (
  id VARCHAR(255) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  year INTEGER NOT NULL,
  genre VARCHAR(255) NOT NULL,
  performer VARCHAR(255) NOT NULL,
  duration INTEGER,
  album_id VARCHAR(255) REFERENCES albums(id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);